use std::env;
use std::fs::{self, File};
use std::io::Write;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let config_path = format!("{}/testcases/config.json", manifest_dir);
 
    let json_str = fs::read_to_string(&config_path).expect("Failed to read config.json");
    let json: serde_json::Value = serde_json::from_str(&json_str).expect("Invalid JSON");

    let testcases = json["testcases"].as_array().expect("Expected testcases array");

    let mut generated = String::new();
    generated.push_str("// Auto-generated by build.rs\n");
    generated.push_str("use std::collections::HashMap;\n\n");
    generated.push_str("pub fn get_file_contents_map() -> HashMap<u32, &'static [u8]> {\n");
    generated.push_str("    let mut m: HashMap<u32, &'static [u8]> = HashMap::new();\n");

    for testcase in testcases {
        let id = testcase["id"].as_u64().expect("id missing") as u32;
        let file_path = testcase["file"].as_str().unwrap();
        generated.push_str(&format!("    m.insert({}, include_bytes!(\"../{}\"));\n", id, file_path));
    }
    generated.push_str("    m\n}\n\n");

    generated.push_str("pub fn get_metadata_map() -> HashMap<u32, (&'static str, &'static str)> {\n");
    generated.push_str("    let mut m = HashMap::new();\n");

    for testcase in testcases {
        let id = testcase["id"].as_u64().unwrap() as u32;
        let details = testcase["details"].as_str().unwrap().replace("\"", "\\\"");
        let typ = testcase["type"].as_str().unwrap();
        generated.push_str(&format!(
            "    m.insert({}, (\"{}\", \"{}\"));\n",
            id, details, typ
        ));
    }
    generated.push_str("    m\n}\n");

    let api_config_path = format!("{}/testapi/config.json", manifest_dir);
    let api_config_str = fs::read_to_string(&api_config_path).expect("Failed to read api_config.json");
    let api_config_json: serde_json::Value = serde_json::from_str(&api_config_str).expect("Invalid JSON");

    let apifiles = api_config_json["apifiles"].as_array().expect("Expected apifiles array");
    let idconfig = api_config_json["idconfig"].as_str().expect("Expected idconfig string");

    // Prepare code snippet for apifiles vec
    let mut api_files_code = String::new();
    api_files_code.push_str("pub fn get_api_files() -> Vec<&'static [u8]> {\n");
    api_files_code.push_str("    vec![\n");
    for file_value in apifiles {
        let file_path = file_value.as_str().unwrap();
        api_files_code.push_str(&format!("        include_bytes!(\"{}\"),\n", file_path));
    }
    api_files_code.push_str("    ]\n}\n\n");

    // Prepare code snippet for idconfig standalone constant
    let idconfig_code = format!(
        "pub const ID_CONFIG: &[u8] = include_bytes!(\"{}\");\n",
        idconfig
    );

    let out_path = Path::new(&manifest_dir).join("src/generated_assets.rs");
    let mut out_file = File::create(out_path).unwrap();
    out_file.write_all(generated.as_bytes()).unwrap();
    out_file.write_all(api_files_code.as_bytes()).unwrap();
    out_file.write_all(idconfig_code.as_bytes()).unwrap();
}