// Auto-generated by build.rs
use std::collections::HashMap;

pub fn get_file_contents_map() -> HashMap<u32, &'static [u8]> {
    let mut m: HashMap<u32, &'static [u8]> = HashMap::new();
    m.insert(1, include_bytes!(".././testcases/colspan/addrowsuccesswithoutcolspan.js"));
    m.insert(2, include_bytes!(".././testcases/colspan/addrowsuccesscolspan2.js"));
    m.insert(3, include_bytes!(".././testcases/rowspan/addsimplerow.js"));
    m.insert(4, include_bytes!(".././testcases/rowspan/adddoublerow.js"));
    m.insert(5, include_bytes!(".././testcases/validationcolspan/formvalidationmissall.js"));
    m.insert(6, include_bytes!(".././testcases/validationcolspan/formvalidationmissfirst.js"));
    m.insert(7, include_bytes!(".././testcases/validationcolspan/formvalidationmisssecond.js"));
    m.insert(8, include_bytes!(".././testcases/validationcolspan/formvalidationmissthird.js"));
    m.insert(9, include_bytes!(".././testcases/validationcolspan/formvalidationonlyfirst.js"));
    m.insert(10, include_bytes!(".././testcases/validationcolspan/formvalidationonlysecond.js"));
    m.insert(11, include_bytes!(".././testcases/validationcolspan/formvalidationonlythird.js"));
    m.insert(12, include_bytes!(".././testcases/validationrowspan/formvalidationmissall.js"));
    m.insert(13, include_bytes!(".././testcases/validationrowspan/formvalidationmissfirst.js"));
    m.insert(14, include_bytes!(".././testcases/validationrowspan/formvalidationmisssecond.js"));
    m.insert(15, include_bytes!(".././testcases/validationrowspan/formvalidationmissthird.js"));
    m.insert(16, include_bytes!(".././testcases/validationrowspan/formvalidationonlyfirst.js"));
    m.insert(17, include_bytes!(".././testcases/validationrowspan/formvalidationonlysecond.js"));
    m.insert(18, include_bytes!(".././testcases/validationrowspan/formvalidationonlythird.js"));
    m
}

pub fn get_metadata_map() -> HashMap<u32, (&'static str, &'static str)> {
    let mut m = HashMap::new();
    m.insert(1, ("colspan táblázathoz hozzáadunk colspan nélküli sort", "colspan"));
    m.insert(2, ("colspan táblázathoz hozzáadunk colspanos sort", "colspan"));
    m.insert(3, ("rowspanos táblázathoz hozzáadunk szimpla sort", "rowspan"));
    m.insert(4, ("rowspanos táblázathoz hozzáadunk dupla sort", "rowspan"));
    m.insert(5, ("validációs üzenetek megjelennek ha nincs kitöltve egy mező sem", "colspan"));
    m.insert(6, ("validációs üzenet megjelenik ha nincs kitöltve az első mező", "colspan"));
    m.insert(7, ("validációs üzenet megjelenik ha nincs kitöltve a második mező", "colspan"));
    m.insert(8, ("validációs üzenet megjelenik ha nincs kitöltve a harmadik mező", "colspan"));
    m.insert(9, ("validációs üzenet megjelenik ha csak az első mező van kitöltve", "colspan"));
    m.insert(10, ("validációs üzenet megjelenik ha csak a második mező van kitöltve", "colspan"));
    m.insert(11, ("validációs üzenet megjelenik ha csak a harmadik mező van kitöltve", "colspan"));
    m.insert(12, ("validációs üzenetek megjelennek ha nincs kitöltve egy mező sem", "rowspan"));
    m.insert(13, ("validációs üzenet megjelenik ha nincs kitöltve az első mező", "rowspan"));
    m.insert(14, ("validációs üzenet megjelenik ha nincs kitöltve a második mező", "rowspan"));
    m.insert(15, ("validációs üzenet megjelenik ha nincs kitöltve a harmadik mező", "rowspan"));
    m.insert(16, ("validációs üzenet megjelenik ha csak az első mező van kitöltve", "rowspan"));
    m.insert(17, ("validációs üzenet megjelenik ha csak a második mező van kitöltve", "rowspan"));
    m.insert(18, ("validációs üzenet megjelenik ha csak a harmadik mező van kitöltve", "rowspan"));
    m
}
pub fn get_api_files() -> Vec<&'static [u8]> {
    vec![
        include_bytes!("../testapi/assert.js"),
        include_bytes!("../testapi/query.js"),
        include_bytes!("../testapi/test.js"),
    ]
}

pub const ID_CONFIG: &[u8] = include_bytes!("../testapi/initid.js");
